"""Seed the catalog collection with roles and skills across all major industries.

Run once after first deploy:
    python seed_catalog.py
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from config import settings

# ── Roles ─────────────────────────────────────────────────────────────────────

ROLES = [
    # Technology
    ("Software Engineer", "Technology"),
    ("Senior Software Engineer", "Technology"),
    ("Staff Software Engineer", "Technology"),
    ("Principal Engineer", "Technology"),
    ("Frontend Developer", "Technology"),
    ("Backend Developer", "Technology"),
    ("Full Stack Developer", "Technology"),
    ("Mobile Developer", "Technology"),
    ("iOS Developer", "Technology"),
    ("Android Developer", "Technology"),
    ("DevOps Engineer", "Technology"),
    ("Site Reliability Engineer", "Technology"),
    ("Platform Engineer", "Technology"),
    ("Cloud Architect", "Technology"),
    ("Solutions Architect", "Technology"),
    ("Data Engineer", "Technology"),
    ("Data Scientist", "Technology"),
    ("Machine Learning Engineer", "Technology"),
    ("AI Engineer", "Technology"),
    ("MLOps Engineer", "Technology"),
    ("Security Engineer", "Technology"),
    ("Cybersecurity Analyst", "Technology"),
    ("Penetration Tester", "Technology"),
    ("QA Engineer", "Technology"),
    ("Automation Engineer", "Technology"),
    ("Embedded Systems Engineer", "Technology"),
    ("Firmware Engineer", "Technology"),
    ("Blockchain Developer", "Technology"),
    ("Game Developer", "Technology"),
    ("Technical Lead", "Technology"),
    ("Engineering Manager", "Technology"),
    ("VP of Engineering", "Technology"),
    ("CTO", "Technology"),

    # Product & Design
    ("Product Manager", "Product"),
    ("Senior Product Manager", "Product"),
    ("Principal Product Manager", "Product"),
    ("Product Owner", "Product"),
    ("UX Designer", "Design"),
    ("UI Designer", "Design"),
    ("UX Researcher", "Design"),
    ("Product Designer", "Design"),
    ("Visual Designer", "Design"),
    ("Graphic Designer", "Design"),
    ("Motion Designer", "Design"),
    ("Brand Designer", "Design"),
    ("Industrial Designer", "Design"),
    ("Interior Designer", "Design"),
    ("Architectural Designer", "Design"),

    # Animation & Film
    ("3D Animator", "Animation & Film"),
    ("2D Animator", "Animation & Film"),
    ("Character Animator", "Animation & Film"),
    ("VFX Artist", "Animation & Film"),
    ("Motion Graphics Artist", "Animation & Film"),
    ("Compositor", "Animation & Film"),
    ("Rigging Artist", "Animation & Film"),
    ("3D Modeller", "Animation & Film"),
    ("Texture Artist", "Animation & Film"),
    ("Lighting Artist", "Animation & Film"),
    ("Storyboard Artist", "Animation & Film"),
    ("Concept Artist", "Animation & Film"),
    ("Technical Director", "Animation & Film"),
    ("Animation Director", "Animation & Film"),
    ("Creative Director", "Animation & Film"),
    ("Film Director", "Animation & Film"),
    ("Video Producer", "Animation & Film"),
    ("Video Editor", "Animation & Film"),
    ("Cinematographer", "Animation & Film"),
    ("Colorist", "Animation & Film"),
    ("Sound Designer", "Animation & Film"),
    ("Corporate Video Producer", "Animation & Film"),

    # Engineering (non-software)
    ("Mechanical Engineer", "Engineering"),
    ("Civil Engineer", "Engineering"),
    ("Structural Engineer", "Engineering"),
    ("Electrical Engineer", "Engineering"),
    ("Chemical Engineer", "Engineering"),
    ("Environmental Engineer", "Engineering"),
    ("Aerospace Engineer", "Engineering"),
    ("Manufacturing Engineer", "Engineering"),
    ("Process Engineer", "Engineering"),
    ("Quality Engineer", "Engineering"),
    ("Robotics Engineer", "Engineering"),
    ("Instrumentation Engineer", "Engineering"),
    ("Petroleum Engineer", "Engineering"),
    ("Biomedical Engineer", "Engineering"),
    ("Project Engineer", "Engineering"),

    # Education
    ("Teacher", "Education"),
    ("Primary School Teacher", "Education"),
    ("Secondary School Teacher", "Education"),
    ("Professor", "Education"),
    ("Lecturer", "Education"),
    ("Curriculum Developer", "Education"),
    ("Instructional Designer", "Education"),
    ("Special Education Teacher", "Education"),
    ("ESL Teacher", "Education"),
    ("School Counsellor", "Education"),
    ("Academic Advisor", "Education"),
    ("Principal", "Education"),
    ("Training Manager", "Education"),
    ("Corporate Trainer", "Education"),
    ("E-Learning Developer", "Education"),

    # Culinary & Hospitality
    ("Chef", "Culinary"),
    ("Executive Chef", "Culinary"),
    ("Sous Chef", "Culinary"),
    ("Pastry Chef", "Culinary"),
    ("Line Cook", "Culinary"),
    ("Catering Manager", "Culinary"),
    ("Food & Beverage Manager", "Culinary"),
    ("Sommelier", "Culinary"),
    ("Barista", "Culinary"),
    ("Restaurant Manager", "Hospitality"),
    ("Hotel Manager", "Hospitality"),
    ("Front Desk Manager", "Hospitality"),
    ("Guest Relations Manager", "Hospitality"),
    ("Event Coordinator", "Hospitality"),
    ("Wedding Planner", "Hospitality"),
    ("Travel Agent", "Hospitality"),
    ("Tour Guide", "Hospitality"),

    # HR & People
    ("HR Manager", "Human Resources"),
    ("HR Business Partner", "Human Resources"),
    ("Talent Acquisition Specialist", "Human Resources"),
    ("Recruiter", "Human Resources"),
    ("Technical Recruiter", "Human Resources"),
    ("Compensation & Benefits Analyst", "Human Resources"),
    ("Learning & Development Manager", "Human Resources"),
    ("People Operations Manager", "Human Resources"),
    ("Employee Relations Manager", "Human Resources"),
    ("HR Generalist", "Human Resources"),
    ("Chief People Officer", "Human Resources"),

    # Marketing & Communications
    ("Marketing Manager", "Marketing"),
    ("Digital Marketing Manager", "Marketing"),
    ("Content Marketing Manager", "Marketing"),
    ("SEO Specialist", "Marketing"),
    ("PPC Specialist", "Marketing"),
    ("Social Media Manager", "Marketing"),
    ("Brand Manager", "Marketing"),
    ("Growth Manager", "Marketing"),
    ("Copywriter", "Marketing"),
    ("Content Writer", "Marketing"),
    ("Technical Writer", "Marketing"),
    ("Public Relations Manager", "Marketing"),
    ("Communications Manager", "Marketing"),
    ("Community Manager", "Marketing"),
    ("CMO", "Marketing"),

    # Sales & Business Development
    ("Sales Representative", "Sales"),
    ("Account Executive", "Sales"),
    ("Account Manager", "Sales"),
    ("Business Development Manager", "Sales"),
    ("Sales Manager", "Sales"),
    ("VP of Sales", "Sales"),
    ("Customer Success Manager", "Sales"),
    ("Solutions Engineer", "Sales"),
    ("Pre-Sales Consultant", "Sales"),
    ("Inside Sales Representative", "Sales"),

    # Finance & Accounting
    ("Financial Analyst", "Finance"),
    ("Senior Financial Analyst", "Finance"),
    ("FP&A Manager", "Finance"),
    ("Controller", "Finance"),
    ("CFO", "Finance"),
    ("Accountant", "Finance"),
    ("Management Accountant", "Finance"),
    ("Auditor", "Finance"),
    ("Tax Specialist", "Finance"),
    ("Investment Analyst", "Finance"),
    ("Portfolio Manager", "Finance"),
    ("Risk Analyst", "Finance"),
    ("Quantitative Analyst", "Finance"),

    # Healthcare
    ("Doctor", "Healthcare"),
    ("General Practitioner", "Healthcare"),
    ("Surgeon", "Healthcare"),
    ("Nurse", "Healthcare"),
    ("Registered Nurse", "Healthcare"),
    ("Pharmacist", "Healthcare"),
    ("Physiotherapist", "Healthcare"),
    ("Dentist", "Healthcare"),
    ("Psychologist", "Healthcare"),
    ("Radiologist", "Healthcare"),
    ("Medical Director", "Healthcare"),
    ("Healthcare Administrator", "Healthcare"),
    ("Clinical Research Coordinator", "Healthcare"),

    # Operations & Management
    ("Operations Manager", "Operations"),
    ("General Manager", "Operations"),
    ("COO", "Operations"),
    ("CEO", "Operations"),
    ("Project Manager", "Operations"),
    ("Program Manager", "Operations"),
    ("Strategy Manager", "Operations"),
    ("Business Analyst", "Operations"),
    ("Management Consultant", "Operations"),
    ("Supply Chain Manager", "Operations"),
    ("Logistics Manager", "Operations"),
    ("Procurement Manager", "Operations"),
    ("Facilities Manager", "Operations"),

    # Legal
    ("Lawyer", "Legal"),
    ("Solicitor", "Legal"),
    ("Barrister", "Legal"),
    ("Legal Counsel", "Legal"),
    ("Compliance Manager", "Legal"),
    ("Paralegal", "Legal"),
    ("Contract Manager", "Legal"),

    # Architecture & Construction
    ("Architect", "Architecture"),
    ("Urban Planner", "Architecture"),
    ("Landscape Architect", "Architecture"),
    ("Site Manager", "Construction"),
    ("Construction Manager", "Construction"),
    ("Quantity Surveyor", "Construction"),

    # Science & Research
    ("Research Scientist", "Science"),
    ("Data Analyst", "Science"),
    ("Biologist", "Science"),
    ("Chemist", "Science"),
    ("Physicist", "Science"),
    ("Environmental Scientist", "Science"),
    ("Lab Technician", "Science"),

    # Creative & Media
    ("Photographer", "Creative"),
    ("Videographer", "Creative"),
    ("Podcast Producer", "Creative"),
    ("Journalist", "Creative"),
    ("Editor", "Creative"),
    ("Music Producer", "Creative"),
    ("Musician", "Creative"),
    ("Actor", "Creative"),
    ("Voice Actor", "Creative"),
    ("Fashion Designer", "Creative"),
    ("Stylist", "Creative"),
]

# ── Skills ────────────────────────────────────────────────────────────────────

SKILLS = [
    # Programming Languages
    ("Python", "Programming"),
    ("JavaScript", "Programming"),
    ("TypeScript", "Programming"),
    ("Java", "Programming"),
    ("C++", "Programming"),
    ("C#", "Programming"),
    ("Go", "Programming"),
    ("Rust", "Programming"),
    ("Swift", "Programming"),
    ("Kotlin", "Programming"),
    ("PHP", "Programming"),
    ("Ruby", "Programming"),
    ("R", "Programming"),
    ("MATLAB", "Programming"),
    ("Scala", "Programming"),
    ("Dart", "Programming"),
    ("Lua", "Programming"),

    # Web Frontend
    ("React", "Frontend"),
    ("Next.js", "Frontend"),
    ("Vue.js", "Frontend"),
    ("Angular", "Frontend"),
    ("HTML", "Frontend"),
    ("CSS", "Frontend"),
    ("TailwindCSS", "Frontend"),
    ("Sass/SCSS", "Frontend"),
    ("Redux", "Frontend"),
    ("Webpack", "Frontend"),
    ("Vite", "Frontend"),

    # Web Backend
    ("Node.js", "Backend"),
    ("FastAPI", "Backend"),
    ("Django", "Backend"),
    ("Flask", "Backend"),
    ("Express.js", "Backend"),
    ("Spring Boot", "Backend"),
    ("Rails", "Backend"),
    ("Laravel", "Backend"),
    ("ASP.NET", "Backend"),
    ("GraphQL", "Backend"),
    ("REST API", "Backend"),
    ("gRPC", "Backend"),

    # Databases
    ("PostgreSQL", "Database"),
    ("MySQL", "Database"),
    ("MongoDB", "Database"),
    ("Redis", "Database"),
    ("Elasticsearch", "Database"),
    ("SQLite", "Database"),
    ("Oracle", "Database"),
    ("MS SQL Server", "Database"),
    ("Cassandra", "Database"),
    ("DynamoDB", "Database"),
    ("Snowflake", "Database"),
    ("BigQuery", "Database"),

    # Cloud & DevOps
    ("AWS", "Cloud"),
    ("GCP", "Cloud"),
    ("Azure", "Cloud"),
    ("Docker", "DevOps"),
    ("Kubernetes", "DevOps"),
    ("Terraform", "DevOps"),
    ("Ansible", "DevOps"),
    ("CI/CD", "DevOps"),
    ("GitHub Actions", "DevOps"),
    ("Jenkins", "DevOps"),
    ("Linux", "DevOps"),
    ("Bash", "DevOps"),
    ("Nginx", "DevOps"),

    # AI / ML
    ("Machine Learning", "AI/ML"),
    ("Deep Learning", "AI/ML"),
    ("TensorFlow", "AI/ML"),
    ("PyTorch", "AI/ML"),
    ("Scikit-learn", "AI/ML"),
    ("NLP", "AI/ML"),
    ("Computer Vision", "AI/ML"),
    ("LangChain", "AI/ML"),
    ("OpenAI API", "AI/ML"),
    ("Prompt Engineering", "AI/ML"),
    ("Data Analysis", "AI/ML"),
    ("Pandas", "AI/ML"),
    ("NumPy", "AI/ML"),

    # Design & Creative Tools
    ("Figma", "Design Tools"),
    ("Adobe Photoshop", "Design Tools"),
    ("Adobe Illustrator", "Design Tools"),
    ("Adobe InDesign", "Design Tools"),
    ("Adobe XD", "Design Tools"),
    ("Sketch", "Design Tools"),
    ("Canva", "Design Tools"),
    ("Framer", "Design Tools"),
    ("Prototyping", "Design Tools"),
    ("User Research", "Design Tools"),
    ("Wireframing", "Design Tools"),
    ("Typography", "Design Tools"),
    ("Brand Identity", "Design Tools"),
    ("Print Design", "Design Tools"),

    # Animation & VFX
    ("Maya", "Animation"),
    ("Blender", "Animation"),
    ("Cinema 4D", "Animation"),
    ("After Effects", "Animation"),
    ("Premiere Pro", "Animation"),
    ("Houdini", "Animation"),
    ("Nuke", "Animation"),
    ("DaVinci Resolve", "Animation"),
    ("3ds Max", "Animation"),
    ("ZBrush", "Animation"),
    ("Substance Painter", "Animation"),
    ("Unity", "Animation"),
    ("Unreal Engine", "Animation"),
    ("Motion Graphics", "Animation"),
    ("Rigging", "Animation"),
    ("Character Animation", "Animation"),
    ("Compositing", "Animation"),
    ("Visual Effects (VFX)", "Animation"),
    ("Storyboarding", "Animation"),
    ("Concept Art", "Animation"),

    # Engineering (non-software)
    ("AutoCAD", "Engineering Tools"),
    ("SolidWorks", "Engineering Tools"),
    ("CATIA", "Engineering Tools"),
    ("ANSYS", "Engineering Tools"),
    ("MATLAB", "Engineering Tools"),
    ("LabVIEW", "Engineering Tools"),
    ("PLC Programming", "Engineering Tools"),
    ("Lean Manufacturing", "Engineering"),
    ("Six Sigma", "Engineering"),
    ("Finite Element Analysis", "Engineering"),
    ("Structural Analysis", "Engineering"),
    ("Project Engineering", "Engineering"),
    ("Quality Assurance", "Engineering"),

    # Education & Training
    ("Curriculum Development", "Education"),
    ("Lesson Planning", "Education"),
    ("Instructional Design", "Education"),
    ("E-Learning Development", "Education"),
    ("Articulate Storyline", "Education"),
    ("Learning Management Systems", "Education"),
    ("Classroom Management", "Education"),
    ("Student Assessment", "Education"),
    ("Special Education", "Education"),
    ("Tutoring", "Education"),

    # Culinary
    ("Menu Planning", "Culinary"),
    ("Food Safety (HACCP)", "Culinary"),
    ("Pastry & Baking", "Culinary"),
    ("Fine Dining", "Culinary"),
    ("Food Styling", "Culinary"),
    ("Kitchen Management", "Culinary"),
    ("Inventory Management", "Culinary"),
    ("Wine Pairing", "Culinary"),
    ("Catering", "Culinary"),

    # HR & People
    ("Talent Acquisition", "HR"),
    ("Applicant Tracking Systems", "HR"),
    ("Employee Relations", "HR"),
    ("Performance Management", "HR"),
    ("Compensation & Benefits", "HR"),
    ("HRIS", "HR"),
    ("Workforce Planning", "HR"),
    ("Onboarding", "HR"),
    ("Diversity & Inclusion", "HR"),
    ("Labour Law", "HR"),
    ("Coaching & Mentoring", "HR"),

    # Marketing & Growth
    ("SEO", "Marketing"),
    ("SEM / PPC", "Marketing"),
    ("Google Analytics", "Marketing"),
    ("Google Ads", "Marketing"),
    ("Meta Ads", "Marketing"),
    ("Email Marketing", "Marketing"),
    ("HubSpot", "Marketing"),
    ("Salesforce", "Marketing"),
    ("Content Marketing", "Marketing"),
    ("Copywriting", "Marketing"),
    ("Social Media Marketing", "Marketing"),
    ("Influencer Marketing", "Marketing"),
    ("A/B Testing", "Marketing"),
    ("Conversion Rate Optimisation", "Marketing"),
    ("Brand Strategy", "Marketing"),
    ("Market Research", "Marketing"),

    # Finance
    ("Financial Modelling", "Finance"),
    ("Excel / VBA", "Finance"),
    ("Power BI", "Finance"),
    ("Tableau", "Finance"),
    ("Accounting", "Finance"),
    ("GAAP / IFRS", "Finance"),
    ("Budgeting & Forecasting", "Finance"),
    ("Tax Planning", "Finance"),
    ("Audit", "Finance"),
    ("Bloomberg Terminal", "Finance"),
    ("Valuation", "Finance"),
    ("Risk Management", "Finance"),

    # Healthcare
    ("Patient Care", "Healthcare"),
    ("Electronic Health Records", "Healthcare"),
    ("Clinical Research", "Healthcare"),
    ("Medical Coding", "Healthcare"),
    ("Pharmacology", "Healthcare"),
    ("Surgical Assistance", "Healthcare"),
    ("Physiotherapy", "Healthcare"),
    ("Mental Health Counselling", "Healthcare"),
    ("Public Health", "Healthcare"),

    # Soft Skills
    ("Leadership", "Soft Skills"),
    ("Communication", "Soft Skills"),
    ("Problem Solving", "Soft Skills"),
    ("Critical Thinking", "Soft Skills"),
    ("Teamwork", "Soft Skills"),
    ("Time Management", "Soft Skills"),
    ("Project Management", "Soft Skills"),
    ("Negotiation", "Soft Skills"),
    ("Presentation Skills", "Soft Skills"),
    ("Stakeholder Management", "Soft Skills"),
    ("Agile / Scrum", "Soft Skills"),
    ("Conflict Resolution", "Soft Skills"),
    ("Decision Making", "Soft Skills"),
    ("Emotional Intelligence", "Soft Skills"),
    ("Cross-functional Collaboration", "Soft Skills"),

    # Tools & Productivity
    ("Jira", "Tools"),
    ("Notion", "Tools"),
    ("Slack", "Tools"),
    ("Microsoft Office", "Tools"),
    ("Google Workspace", "Tools"),
    ("Asana", "Tools"),
    ("Trello", "Tools"),
    ("Confluence", "Tools"),
    ("Zendesk", "Tools"),
    ("Intercom", "Tools"),
    ("Miro", "Tools"),
    ("Zoom", "Tools"),
]


async def seed():
    client = AsyncIOMotorClient(settings.mongodb_uri)
    db = client.tailormycv

    # Drop and recreate for clean seed
    await db.catalog.drop()

    role_docs = [{"type": "role", "name": name, "category": cat} for name, cat in ROLES]
    skill_docs = [{"type": "skill", "name": name, "category": cat} for name, cat in SKILLS]

    await db.catalog.insert_many(role_docs + skill_docs)
    await db.catalog.create_index([("type", 1), ("name", 1)])
    await db.catalog.create_index([("type", 1), ("name", "text")])

    print(f"Seeded {len(role_docs)} roles and {len(skill_docs)} skills.")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
